paths:

  # ARCHIVOS UCLM:

  # SABANA LME: select licencias

#Migracion de CSV/XLS hacia base de datos : Las siguientes configuraciones de encoding y csv_sep ya no son necesarias ya que los datos se cargan desde la base de datos.
#encoding:
#  detalle_uclm: "latin-1"
#  relatos: # Migracion de csv/xlsx a Base de datos : Ya no se utiliza
#csv_sep:
#  detalle_uclm: "|"
#  relatos: ","

filters:
  causal_homologada: "Denuncia a profesional emisor"
  mes_a_revisar: 6
  anio: 2025

semaforo:
  meses: [4, 5, 6, 7]
  rn_ln_mes: 400
  umbral_decorte: 0.5
  umbral_deanomalias: 0.5
  sort_values_by: "um"

prioritization:
  ordenar_por: "Fecha"  # or "Priorización"
  umbral_de_priorizacion: 0.94
  output_filename: "./standalone/reclamos/RESULTADOS.csv"

nlp:
  enabled: true
  model: "es_core_news_sm"  # must be installed separately