CREATE SCHEMA IF NOT EXISTS ml;

DROP TABLE IF EXISTS ml.anomalias;
CREATE SCHEMA IF NOT EXISTS ml;

CREATE TABLE ml.anomalias (
    id_lic BIGINT PRIMARY KEY,
    rut_medico VARCHAR(20),
    rut_trabajador VARCHAR(20),
    rut_empleador VARCHAR(20),
    dias_reposo INT,
    edad_trabajador INT,
    hora_emision INT,
    dia_codificado INT,
    calidad_trabajador_independiente INT,
    calidad_trabajador_dependiente_privado INT,
    calidad_trabajador_publico_afecto INT,
    calidad_trabajador_publico_no_afecto INT,
    recencia_trabajador NUMERIC,
    frecuencia_trabajador_60d NUMERIC,
    frecuencia_trabajador_40d NUMERIC,
    frecuencia_trabajador_20d NUMERIC,
    reposo_trabajador_60d NUMERIC,
    reposo_trabajador_40d NUMERIC,
    reposo_trabajador_20d NUMERIC,
    n_medicos_distintos_xtrabajador_60d INT,
    n_empleadores_distintos_xtrabajador_60d INT,
    desviacion_reposo_trabajador_60d NUMERIC,
    recencia_medico NUMERIC,
    frecuencia_medico_30d NUMERIC,
    frecuencia_medico_15d NUMERIC,
    frecuencia_medico_7d NUMERIC,
    reposo_medico_30d NUMERIC,
    reposo_medico_15d NUMERIC,
    reposo_medico_7d NUMERIC,
    licencias_20_min INT,
    licencias_40_min INT,
    licencias_60_min INT,
    max_licencias_dia_30d INT,
    frecuencia_j_30d_medico INT,
    frecuencia_f_30d_medico INT,
    frecuencia_m_30d_medico INT,
    max_rest_days_30d INT,
    diferencia_dias INT,
    licencias_despues_umbral INT,
    n_trabajadores_distintos_xmedico_60d INT,
    n_empleadores_distintos_xmedico_60d INT,
    hhi_empleadores_por_medico_60d NUMERIC,
    n_remotas_30d INT,
    n_presenciales_30d INT,
    recencia_empleador NUMERIC,
    frecuencia_empleador_60d NUMERIC,
    frecuencia_empleador_40d NUMERIC,
    frecuencia_empleador_20d NUMERIC,
    reposo_empleador_60d NUMERIC,
    reposo_empleador_40d NUMERIC,
    reposo_empleador_20d NUMERIC,
    n_trabajadores_distintos_xempleador_60d INT,
    n_medicos_distintos_xempleador_60d INT,
    frecuencia_j_30d_empleador INT,
    frecuencia_f_30d_empleador INT,
    frecuencia_m_30d_empleador INT,
    historial_trabajador_medico INT,
    historial_empleador_medico INT,
    ponderado_medico_trabajador NUMERIC,
    anomaly_score NUMERIC,
    propensity_score_iforest NUMERIC
);
